{% set name = "staged-script" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  sha256: 7ecea821ee3859c9cf302b3a552d449e93f90be9d9469c0f8a68fe6870a78ea5
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/staged_script-{{ version }}.tar.gz

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - reverse-argparse
    - rich
    - tenacity

test:
  commands:
    - pip check
  imports:
    - staged_script
  requires:
    - pip
    - python {{ python_min }}

about:
  description: |
    Python is an ideal language for certain types of infrastructure automation.
    Automating what a user does manually often involves walking through a
    series of stages.  A user may wish to run all the stages in series, or
    perhaps only a subset, and depending on how things go, certain stages may
    need to be retried.  Once the script finishes running, it'd be ideal if it
    could tell the user exactly what was run, for the sake of easing
    replicability.  staged-script aims to ease the development such automation
    scripts.  It's easy to get started with, but also provides significant
    power-user functionality for those who need it.
  dev_url: https://github.com/sandialabs/staged-script
  doc_url: https://staged-script.readthedocs.io/
  home: https://github.com/sandialabs/staged-script
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: |
    A Python package enabling the development of robust automation scripts that
    are subdivided into stages.

extra:
  recipe-maintainers:
    - jmgate
